# Generated by Django 5.2.5 on 2025-09-13 23:33
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        TrigramExtension()
    ]
